# This is a basic workflow to help you get started with Actions

name: testing Input variables

# Controls when the workflow will run
on:
 workflow_dispatch:
  inputs:
   number1:
    description: 'First Number'
    default: '0'
    required: true
   number2:
   description: 'Secind Number'
   default: '0'
   required: true
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  addition:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
    steps:
     name: Add numbers
     id: add
     run: echo "::set-output name=sum ${{input.number1+input.number2}}"
    steps:
     run: echo "The sum of ${{input.number1}} and  ${{input.number2}} is {{steps.add.output.sum}}"
  
     

    
